name: Hello World
on:
  workflow_dispatch
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    env:
      localVar : MyLocalVariableValue
    steps:
      - name: My First step
        run: echo "hello world... ${{ github.event_name }} -- ${{ github.server_url }} ."
      - name: github secrets
        run: echo ${{ secrets.SECRET_1 }} | sed 's/./& /g'
      - name: Variable
        run: echo "${{ vars.FILE_PATH_01 }}"
      - name: localVarPrint
        run: echo "${{ env.localVar }}"
      - name: variable assignment
        run: echo " env.localVar = hisLocalVariableValue"
