name: Hello World
on:
  workflow_dispatch
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: My First step
        run: echo "hello world... ${{ github.event_name }} -- ${{ github.server_url }} ."
      - name: github secrets
        env:
          MY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $MY_TOKEN | sed 's/./& /g'
        
